data = {
    "J": [
        "a",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "sds",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "s",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    "U": [
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song: 4th Note<br><br>2: A<br>5: C-Down<br>9: C-Right<br>11: C-Left<br>14: C-Up",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song: 5th Note<br><br>2: A<br>5: C-Down<br>9: C-Right<br>11: C-Left<br>14: C-Up",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song: 6th Note<br><br>2: A<br>5: C-Down<br>9: C-Right<br>11: C-Left<br>14: C-Up",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song: 7th Note<br><br>2: A<br>5: C-Down<br>9: C-Right<br>11: C-Left<br>14: C-Up",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song: 8th Note<br><br>2: A<br>5: C-Down<br>9: C-Right<br>11: C-Left<br>14: C-Up",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Scarecrow's Song",
        "Amount of Bombers caught",
        "Bomber Caught 1st",
        "Bomber Caught 2nd",
        "Bomber Caught 3rd",
        "Bomber Caught 4th",
        "Bomber Caught 5th",
        "Day 1 Lottery: 1st digit<br><br>Normal range: [0-9]",
        "Day 1 Lottery: 2nd digit<br><br>Normal range: [0-9]",
        "Day 1 Lottery: 3rd digit<br><br>Normal range: [0-9]",
        "Day 2 Lottery: 1st digit<br><br>Normal range: [0-9]",
        "Day 2 Lottery: 2nd digit<br><br>Normal range: [0-9]",
        "Day 2 Lottery: 3rd digit<br><br>Normal range: [0-9]",
        "Day 3 Lottery: 1st digit<br><br>Normal range: [0-9]",
        "Day 3 Lottery: 2nd digit<br><br>Normal range: [0-9]",
        "Day 3 Lottery: 3rd digit<br><br>Normal range: [0-9]",
        "Oceanside Spider House Mask Code: 1st color<br><br>0: red<br>1: blue<br>2: green<br>3: yellow<br>",
        "Oceanside Spider House Mask Code: 2nd color<br><br>0: red<br>1: blue<br>2: green<br>3: yellow<br>",
        "Oceanside Spider House Mask Code: 3rd color<br><br>0: red<br>1: blue<br>2: green<br>3: yellow<br>",
        "Oceanside Spider House Mask Code: 4th color<br><br>0: red<br>1: blue<br>2: green<br>3: yellow<br>",
        "Oceanside Spider House Mask Code: 5th color<br><br>0: red<br>1: blue<br>2: green<br>3: yellow<br>",
        "Oceanside Spider House Mask Code: 6th color<br><br>0: red<br>1: blue<br>2: green<br>3: yellow<br>",
        "Bomber Code: 1st digit<br><br>Normal range: [1-5]",
        "Bomber Code: 2nd digit<br><br>Normal range: [1-5]",
        "Bomber Code: 3rd digit<br><br>Normal range: [1-5]",
        "Bomber Code: 4th digit<br><br>Normal range: [1-5]",
        "Bomber Code: 5th digit<br><br>Normal range: [1-5]",
        "Epona: Stored Scene number (short)<br><br>This is the first byte of a short which stores the scene Epona was in when you got off her last. A list of scenes can be found <a href=\"https://docs.google.com/spreadsheets/d/1J-4OwmZzOKEv2hZ7wrygOpMm0YcRnephEo3Q2FooF6E/edit#gid=1593589171\">here</a>.",
        "Epona: Stored Scene number (short)<br><br>This is the second byte of a short which stores the scene Epona was in when you got off her last. A list of scenes can be found <a href=\"https://docs.google.com/spreadsheets/d/1J-4OwmZzOKEv2hZ7wrygOpMm0YcRnephEo3Q2FooF6E/edit#gid=1593589171\">here</a>.",
        "Epona: Stored X-coordinate (short)<br><br>This is the first byte of a short which stores the X-coordinate Epona was at when you last got off of her. Note that this coordinate is stored as a short, unlike most coordinates, which are stored as floats.",
        "Epona: Stored X-coordinate (short)<br><br>This is the second byte of a short which stores the X-coordinate Epona was at when you last got off of her. Note that this coordinate is stored as a short, unlike most coordinates, which are stored as floats.",
        "Epona: Stored Y-coordinate (short)<br><br>This is the first byte of a short which stores the Y-coordinate Epona was at when you last got off of her. Note that this coordinate is stored as a short, unlike most coordinates, which are stored as floats.",
        "Epona: Stored Y-coordinate (short)<br><br>This is the second byte of a short which stores the Y-coordinate Epona was at when you last got off of her. Note that this coordinate is stored as a short, unlike most coordinates, which are stored as floats.",
        "Epona: Stored Z-coordinate (short)<br><br>This is the second byte of a short which stores the Z-coordinate Epona was at when you last got off of her. Note that this coordinate is stored as a short, unlike most coordinates, which are stored as floats.",
        "Epona: Stored Z-coordinate (short)<br><br>This is the second byte of a short which stores the Z-coordinate Epona was at when you last got off of her. Note that this coordinate is stored as a short, unlike most coordinates, which are stored as floats.",
        "Epona: Stored Angle (short)<br><br>This is the first byte of a short which stores the angle Epona was facing when you last got off of her.",
        "Epona: Stored Angle (short)<br><br>This is the second byte of a short which stores the angle Epona was facing when you last got off of her.",
        "Checksum<br><br>This is an unsigned 16-bit integer which sums the bytes from the start of save context up to this point",
        "Checksum<br><br>This is an unsigned 16-bit integer which sums the bytes from the start of save context up to this point",
        "event_inf[0]: <br><br>This is a table of various flags for events throughout the game. A list of these flags can be found here: <a href=\"https://docs.google.com/spreadsheets/d/181V9dR5vBROdCVB4FkljG5oz2O4gGU5OTAkoPQX9X10/edit#gid=1676188860\">event_inf</a>",
        "event_inf[1]: <br><br>This is a table of various flags for events throughout the game. A list of these flags can be found here: <a href=\"https://docs.google.com/spreadsheets/d/181V9dR5vBROdCVB4FkljG5oz2O4gGU5OTAkoPQX9X10/edit#gid=1676188860\">event_inf</a>",
        "event_inf[2]: <br><br>This is a table of various flags for events throughout the game. A list of these flags can be found here: <a href=\"https://docs.google.com/spreadsheets/d/181V9dR5vBROdCVB4FkljG5oz2O4gGU5OTAkoPQX9X10/edit#gid=1676188860\">event_inf</a>",
        "event_inf[3]: <br><br>This is a table of various flags for events throughout the game. A list of these flags can be found here: <a href=\"https://docs.google.com/spreadsheets/d/181V9dR5vBROdCVB4FkljG5oz2O4gGU5OTAkoPQX9X10/edit#gid=1676188860\">event_inf</a>",
        "event_inf[4]: <br><br>This is a table of various flags for events throughout the game. A list of these flags can be found here: <a href=\"https://docs.google.com/spreadsheets/d/181V9dR5vBROdCVB4FkljG5oz2O4gGU5OTAkoPQX9X10/edit#gid=1676188860\">event_inf</a>",
        "event_inf[5]: <br><br>This is a table of various flags for events throughout the game. A list of these flags can be found here: <a href=\"https://docs.google.com/spreadsheets/d/181V9dR5vBROdCVB4FkljG5oz2O4gGU5OTAkoPQX9X10/edit#gid=1676188860\">event_inf</a>",
        "event_inf[6]: <br><br>This is a table of various flags for events throughout the game. A list of these flags can be found here: <a href=\"https://docs.google.com/spreadsheets/d/181V9dR5vBROdCVB4FkljG5oz2O4gGU5OTAkoPQX9X10/edit#gid=1676188860\">event_inf</a>",
        "event_inf[7]: <br><br>This is a table of various flags for events throughout the game. A list of these flags can be found here: <a href=\"https://docs.google.com/spreadsheets/d/181V9dR5vBROdCVB4FkljG5oz2O4gGU5OTAkoPQX9X10/edit#gid=1676188860\">event_inf</a>",
        "Rock Sirloin Flag<br><br>This is a flag which determines whether or not to load the rock sirloin in Link's hands on the next scene load. A value of 0 will not load the Rock Sirloin, but any non-zero value will cause it to be loaded.",
        "B Button disabler<br><br>B button will be disabled if set to 255",
        "Blue Bubble Jinx Timer (short)<br><br>Normally gets set to 1200 when hit by a bubble and counts down 1 per frame, so it lasts 1 minute. You cannot draw your sword while jinxed.",
        "Blue Bubble Jinx Timer (short)<br><br>Normally gets set to 1200 when hit by a bubble and counts down 1 per frame, so it lasts 1 minute. You cannot draw your sword while jinxed.",
        "Rupee Accumulator (short)<br><br>Counts down by 1 each frame, gives 1 rupee each time it counts down",
        "Rupee Accumulator (short)<br><br>Counts down by 1 each frame, gives 1 rupee each time it counts down",
        "HSW Timer: 1<br><br>Set to 1 when you catch hot spring water in the 1st bottle slot.",
        "HSW Timer: 2<br><br>Set to 1 when you catch hot spring water in the 2nd bottle slot.",
        "HSW Timer: 3<br><br>Set to 1 when you catch hot spring water in the 3rd bottle slot.",
        "HSW Timer: 4<br><br>Set to 1 when you catch hot spring water in the 4th bottle slot.",
        "HSW Timer: 5<br><br>Set to 1 when you catch hot spring water in the 5th bottle slot.",
        "HSW Timer: 6<br><br>Set to 1 when you catch hot spring water in the 6th bottle slot.",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 1",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 2",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 3",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 4",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 5",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "HSW Timer: 6",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row).",
        "Pictograph Picture:<br><br>The entire picture is 160 by 112 pixels. It uses 5 bits per pixel (100 bytes per row)."
    ]
}
